### ISSUE TITLE
g:todo_browser Configuration Setting

### ISSUE THREAD

**Issue by bradjadkins** [mivok/vimtodo#1]
Unable to get this to work properly on Win7 when using Firefox (spaces in path?) I had to add the Firefox path to the system PATH and then configure g:todo_browser="firefox.exe" in order to get this to work. Also, I can not use Vim until the browser session is closed. Launching the browser locks Vim in essence. This is unexpected behavior, I expected to be able to go back and forth between the two (launch as a separate process?). I am running Vim 7.2.

**Comment by bradjadkins** [comment]
I have this working using Perl. I created a Perl app that does an exec(), which starts firefox passing the link under the cursor. The same Perl app also loads the tid url using the tid under the cursor. The key is adding a menu item to call the app. The Perl app is ff.pl. I added:

menu Todo.Browse\ To\ Address\ or\ TID :!start perl C:\apps\bin\ff.pl <C-R><C-W><CR>

This works very nicely. !start allows you to return to Vim and leave the browser open for as long as you like. Here is the Perl app:

Caveat: firefox.exe must be in your path.

my $tid_url = 'http://task_management_system/~tid~tid_username~tid_password
my $tid_username = '*******_';
my $tid_password = '**_*****';

my $link = $ARGV[0];

if ( $link =~ /^CR(\d\d\d\d\d)$|^tid(\d\d\d\d\d)$/i ) {
    my $crn = $1;
    $link = $tid_url;
    $link =~ s/~tid/$crn/;
    $link =~ s/~tid_username/$tid_username/;
    $link =~ s/~tid_password/$tid_password/;
}

exec 'firefox', $link;
exit 0;

**Comment by mivok** [comment]
I've just committed a fix for the spaces in your browser path issue.

Regarding the vim hanging while the browser is open - the browser path needs to be something that will return once it has opened the page. On linux I use 'gnome-open', and on mac the 'open' command should work. Both of these open up the default browser and return to vim. Your fix seems to suggest that setting the browser to start.exe (or just start) might do the same thing. I don't have a windows machine to test on, but if start.exe will accept a URL as well as a filename, it should work as you want.

Let me know if it works for you.
