### ISSUE TITLE
Support for Time on Task

### ISSUE THREAD

**Issue by bradjadkins** [mivok/vimtodo#2]
I would like to see support for "time spent on tasks". Something simple, perhaps along the lines of allowing collection of hours on each task, then roll that task totals up to a todo record total. So mabye something like this, where time on task is in braces after the task description:

```
[ ] Task 1 [0.0]
[X] Task 2 [1.5]
[ ] Task 3 [0.5]
```

These would roll up to a total time on task of 2.0 and that would be added somewhere, maybe in the LOGBOOK drawer would be nice.

Thanks for a great tool.

**Comment by mivok** [comment]
Time spent on tasks support (Closed by c8a602e8b12109b1120005db6fa464b724d597c6)

Store total time spent on tasks in an INFO drawer

**Comment by mivok** [comment]
I've just committed an implementation of this - the tag format is [1.5h], and the total time is added to a new INFO drawer - I plan to make this configurable if needed.
