### ISSUE TITLE
Allow customising s:PropertyVars

### ISSUE THREAD

**Issue by khorser** [mivok/vimtodo#5]
I am extending vimtodo with my after/ftplugin and after/syntax scripts.
One of the things I'd like to do is store custom information in the drawer. If s:PropertyVars were allowed to be extended it would save me from copy-pasting s:LoadFileVars or modifying ftplugin/todo.vim to get my custom setting.

**Comment by mivok** [comment]
Hi,

I'm glad to hear that you're using vimtodo.

I've just pushed a change that lets you set g:todo_property_vars and g:todo_property_types in your .vimrc to the customproperties branch. Unfortunately, it won't work if you set these variables in the after/ftplugin/todo.vim file, as by that point the variables have already been loaded from the file.

Would this work for your customizations? If so I'll merge into master.

If you need to have something where the only files that need to be modified are in after/ftplugin, the only way I can see to do that would be to make the LoadFileVars function and PropertyVars/PropertyTypes variables public.

What type of extensions have you made so far? If you think they would be useful for others, I'd love to see them. Feel free to send a pull request.

**Comment by khorser** [comment]
I can hardly recall why I needed it. Thanks anyway, I will definitely find
the use for this feature when I return to the project.
On Apr 8, 2012 3:51 AM, "Mark Harrison" <
reply@reply.github.com>
wrote:
