### ISSUE TITLE
(Feature request.) Use strikethrough/strikeout text format for done tasks

### ISSUE THREAD

**Issue by wolterhv** [mivok/vimtodo#8]
For me, striking out a task is what materializes the pleasure of completing it.

**Comment by wolterhv** [comment]
Or if you know how I can implement that on my end, could you please show me?

**Comment by wolterhv** [comment]
I've been reading a bit and it looks like strikethrough text is pretty much impossible in Vim. I would settle for a highlight of some green tone, but I can't figure out how to do it.

**Comment by mivok** [comment]
Try adding the following to your .vimrc:

```
hi def todoDone ctermfg=green guifg=green
```

That should highlight done tasks in green.

**Comment by wolterhv** [comment]
On Sun, 2013-12-22 at 17:17 -0800, Mark Harrison wrote:

> Try adding the following to your .vimrc:
> 
> hi def todoDone ctermfg=green guifg=green
> 
> That should highlight done tasks in green.

I tried the above command, and tried it without the def flag, but in
neither case did it work. After running 

verbose hi todoDone

I was shown that the plugin's syntax/todo.vim script sets the format for
todoDone instead of my ~/.vimrc file.

I understand that in syntax/todo.vim the line to set the format for
todoDone includes the "default" parameter, which is supposed to be
ignored if todoDone is already defined in the session, so I don't
understand why your solution doesn't work. Any ideas?
